name = "binternet"
pages_build_output_dir = ".svelte-kit/cloudflare"
# compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-08-20"

[[d1_databases]]
binding = "DB"
database_name = "inscriptions_db"
database_id = "674e2007-532d-4ad5-839a-a0ee1c7a794e"

[[r2_buckets]]
binding = 'BK'
bucket_name = 'inscriptions-bk'
